spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acquisition?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: WWww123456..
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml